[package]
name = "rayc_ir"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
rayc_arena.path = "../../base/arena"
rayc_qbice.path = "../../base/qbice"
rayc_lexical.path = "../../syntax/lexical"
rayc_type.path = "../type"
rayc_symbol.path = "../symbol"
rayc_semantic_element.path = "../semantic_element"
rayc_hash.path = "../../base/hash"
qbice.workspace = true
derive_more.workspace = true
bon.workspace = true

[lints]
workspace = true
