[workspace]
members = [
    # tidy-alphabetical-start
    "compiler/base/arena",
    "compiler/base/target",
    "compiler/base/source_file",
    "compiler/base/hash",
    "compiler/base/diagnostic",
    "compiler/base/handler",
    "compiler/base/test_input",
    "compiler/base/extend",
    "compiler/base/tokio",
    "compiler/base/qbice",
    "compiler/base/transitive_closure",
    "compiler/base/source_file_impl",

    "compiler/syntax/lexical",
    "compiler/syntax/lexical_impl",
    "compiler/syntax/parser",
    "compiler/syntax/syntax",
    "compiler/syntax/syntax_impl",

    "compiler/semantic/symbol",
    "compiler/semantic/symbol_impl",
    "compiler/semantic/tast_capture_analysis",
    "compiler/semantic/type",
    "compiler/semantic/typed_ast",
    "compiler/semantic/typed_ast_builder",
    "compiler/semantic/ir",
    "compiler/semantic/ir_builder",
    "compiler/semantic/mono_ir",
    "compiler/semantic/mono_ir_builder",
    "compiler/semantic/resolution",
    "compiler/semantic/semantic_element",
    "compiler/semantic/semantic_element_impl",
    "compiler/semantic/solver",
    "compiler/semantic/check",

    "compiler/codegen/c",
    "compiler/codegen/c2",
    "compiler/codegen/mono",

    "compiler/e2e",

    "compiler/driver",
    "compiler/main",

    # tidy-alphabetical-end
]
resolver = "2"

[workspace.dependencies]
mimalloc = { version = "0.1.48" }
derive_more = { version = "2.0.1", features = [
    "display",
    "deref",
    "deref_mut",
    "from",
    "index",
    "index_mut",
] }
inventory = "0.3.2"
im = "15.1.0"
enum-as-inner = "0.6.0"
thiserror = "2.0.12"
getset = "0.1.2"
proptest = "1.9.0"
lazy_static = "1.4.0"
strum = "0.27.1"
strum_macros = "0.27.1"
colored = "3.0.0"
paste = "1.0.12"
tempfile = "3.5.0"
by_address = "1.1.0"
quickcheck = "1.0.3"
itertools = "0.14.0"
parking_lot = { version = "0.12.1" }
derive-new = "0.7.0"
memmap2 = "0.9.3"
ouroboros = "0.18.0"
take_mut = "0.2.2"
rayon = { version = "1.8.0" }
clap = { version = "4.4.0", features = ["derive"] }
walkdir = "2.5.0"
bitflags = "2.4.1"
drain_filter_polyfill = "0.1.3"
typestate = "0.8.0"
enum_dispatch = "0.3.12"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "sync", "macros"] }
static_assertions = "1.1.0"
bimap = "0.6.3"
env_logger = "0.11.0"
log = "0.4.14"
tower-lsp = { version = "0.20.0", features = ["proposed"] }
dashmap = { version = "6.1.0", features = ["rayon"] }
bit-vec = "0.8.0"
displaydoc = "0.2.5"
ron = "0.10.1"
typetag = "0.2.19"
erased-serde = "0.4.5"
indicatif = "0.18.2"
inkwell = { version = "0.5.0", features = ["llvm18-0", "no-libffi-linking"] }
bon = "3.7.0"
assert_cmd = "2.0.16"
backtrace = "0.3.69"
toml = { version = "0.9.8", features = ["display"] }
codespan-reporting = { version = "0.13.1" }
fxhash = "0.2.1"
macro_rules_attribute = { version = "0.2.0", features = ["verbose-expansions"] }
smallbox = { version = "0.8.6" }
quote = { version = "1.0.28", features = ["proc-macro"] }
proc-macro2 = { version = "1.0.28", features = ["proc-macro"] }
syn = { version = "2.0.101", features = ["full", "visit"] }
insta = { version = "1.43.0", features = ["ron", "filters"] }
postcard = { version = "1.1.1", features = ["use-std"] }
termcolor = { version = "1.2.0" }
extend = { version = "1.2.0" }
redb = { version = "3.1.0" }
strsim = { version = "0.11.1" }
tracing = { version = "0.1.40", features = ["std"] }
tracing-subscriber = { version = "0.3.18", features = [
    "std",
    "env-filter",
    "fmt",
    "tracing-log",
] }
extfn = { version = "0.1.1" }
siphasher = "1.0.1"
crossbeam = "0.8.4"
rand = { version = "0.9.2", features = ["std"] }
tracing-chrome = "0.7.2"
serde = { version = "1.0.219", features = ["derive", "std"] }
futures = { version = "0.3.30" }
test-generator = { version = "0.3.1" }
rstest = { version = "0.26.1" }
pretty_assertions = { version = "1.4.1" }
trait-variant = { version = "0.1.2" }
sled = { version = "0.34.7" }
stacker = "0.1.21"
serde_json = { version = "1.0.96" }
fuzzy-matcher = { version = "0.3.7" }
console-subscriber = "0.5.0"
qbice = { version = "0.6.8", features = ["rocksdb"] }
linkme = { version = "0.3.35" }
tikv-jemallocator = { version = "0.6.1", features = [
    "override_allocator_on_supported_platforms",
] }
tikv-jemalloc-ctl = { version = "0.6.1" }
ropey = "1.6.1"
annotate-snippets = "0.12"
ansi_term = "0.12.1"
tokio-util = "0.7.1"

[patch.crates-io]
inkwell = { git = "https://github.com/Simmypeet/inkwell", rev = "4366f7b37b4e732b4c567494077f3d871e2a2a60" }

[workspace.package]
version = "0.1.0-beta.2"
authors = ["Simmypeet"]
description = "The Ray Programming Language Compiler"
edition = "2024"
rust-version = "1.88.0"

[workspace.lints.rust]
missing_copy_implementations = "deny"
missing_debug_implementations = "deny"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
# this generates errors on enum-as-inner in nightly toolchain
double-parens = "allow"
missing_panics_doc = "allow"
missing_errors_doc = "allow"
use_self = "deny"
useless_let_if_seq = "deny"
set_contains_or_insert = "deny"
option_if_let_else = "deny"
needless_collect = "deny"
missing_const_for_fn = "deny"
equatable_if_let = "deny"
redundant_clone = "deny"
cognitive_complexity = "deny"
type_repetition_in_bounds = "deny"
trait_duplication_in_bounds = "deny"
collection_is_never_read = "deny"
branches_sharing_code = "deny"
iter_on_empty_collections = "deny"
iter_on_single_items = "deny"

[workspace.metadata.cargo-machete]
ignored = ["strum"]
