/* This file is auto generated by Ray compiler */
#include <stdint.h>
#include <stdbool.h>

/* Composite type forward declarations */
typedef struct RayTuple_8QIsDe4F9tDtX6oy37oyy RayTuple_8QIsDe4F9tDtX6oy37oyy_t;
typedef struct RayLambda_7PMsPT17QXgvAjKmNfhV5e RayLambda_7PMsPT17QXgvAjKmNfhV5e_t;

/* Composite type definitions */
struct RayLambda_7PMsPT17QXgvAjKmNfhV5e {
    int32_t (*call)(void *env);
    void *env;
};
struct RayTuple_8QIsDe4F9tDtX6oy37oyy {
    int32_t elem0;
    int32_t elem1;
};

/* Lambda capture environment definitions */
struct RayLambdaEnv_readSecond_1gSd8c4SPC41Wbt8MVPJVM_lambda_1 {
    const RayTuple_8QIsDe4F9tDtX6oy37oyy_t* ray_capture_0;
};


/* Function forward declarations */
int32_t ray_readSecond_1gSd8c4SPC41Wbt8MVPJVM(RayTuple_8QIsDe4F9tDtX6oy37oyy_t ray_param_0);
int32_t ray_readSecond_1gSd8c4SPC41Wbt8MVPJVM_lambda_1(void *ray_raw_env);
int32_t ray_main_1gSd8c4SPC41Wbt8MVPJVM(void);

/* Function definitions */
int32_t ray_readSecond_1gSd8c4SPC41Wbt8MVPJVM(RayTuple_8QIsDe4F9tDtX6oy37oyy_t ray_param_0) {
    RayLambda_7PMsPT17QXgvAjKmNfhV5e_t ray_var_0;
    const RayTuple_8QIsDe4F9tDtX6oy37oyy_t* ray_expr_0;
    RayLambda_7PMsPT17QXgvAjKmNfhV5e_t ray_expr_1;
    RayLambda_7PMsPT17QXgvAjKmNfhV5e_t ray_expr_2;
    int32_t ray_expr_3;
    struct RayLambdaEnv_readSecond_1gSd8c4SPC41Wbt8MVPJVM_lambda_1 ray_lambda_env_1;
ray_block_0:
    ray_expr_0 = &(ray_param_0);
    ray_lambda_env_1 = (struct RayLambdaEnv_readSecond_1gSd8c4SPC41Wbt8MVPJVM_lambda_1){ .ray_capture_0 = ray_expr_0 };
    ray_expr_1 = (RayLambda_7PMsPT17QXgvAjKmNfhV5e_t){ .call = ray_readSecond_1gSd8c4SPC41Wbt8MVPJVM_lambda_1, .env = &ray_lambda_env_1 };
    ray_var_0 = ray_expr_1;
    ray_expr_2 = ray_var_0;
    ray_expr_3 = ray_expr_2.call(ray_expr_2.env);
    return ray_expr_3;
}

int32_t ray_readSecond_1gSd8c4SPC41Wbt8MVPJVM_lambda_1(void *ray_raw_env) {
    struct RayLambdaEnv_readSecond_1gSd8c4SPC41Wbt8MVPJVM_lambda_1 *ray_env = ray_raw_env;
    const RayTuple_8QIsDe4F9tDtX6oy37oyy_t* ray_expr_0;
    int32_t ray_expr_1;
ray_block_0:
    ray_expr_0 = ray_env->ray_capture_0;
    ray_expr_1 = (*ray_expr_0).elem1;
    return ray_expr_1;
}

int32_t ray_main_1gSd8c4SPC41Wbt8MVPJVM(void) {
    int32_t ray_expr_0;
    int32_t ray_expr_1;
    RayTuple_8QIsDe4F9tDtX6oy37oyy_t ray_expr_2;
    int32_t ray_expr_3;
ray_block_0:
    ray_expr_0 = 20;
    ray_expr_1 = 27;
    ray_expr_2 = ((RayTuple_8QIsDe4F9tDtX6oy37oyy_t){.elem0 = ray_expr_0,.elem1 = ray_expr_1});
    ray_expr_3 = ray_readSecond_1gSd8c4SPC41Wbt8MVPJVM(ray_expr_2);
    return ray_expr_3;
}

