//! The sections of a generated C translation unit.

use std::fmt::{self, Display, Write as _};

use crate::{
    aggregates::AggregateRegistry,
    c::{aggregate::AggregateDefinition, name::DefinitionName},
};

const PRELUDE: &str = "/* This file is auto generated by the Ray compiler. */\n#include \
                       <stdbool.h>\n#include <stdint.h>\n#include <math.h>\n\n";

const WRITE_TO_STRING: &str = "writing to a String cannot fail";

/// A generated C translation unit.
///
/// Function definitions are appended as fragments are processed; aggregate
/// definitions are added once every aggregate is known, since their order
/// depends on the complete set. The unit renders through [`Display`].
#[derive(Debug, Default)]
pub(crate) struct TranslationUnit {
    aggregate_declarations: String,
    aggregate_definitions: String,
    function_declarations: String,
    function_definitions: String,
}

impl TranslationUnit {
    /// Adds a forward declaration, written without its trailing `;`.
    ///
    /// Every function is declared once, in the order it is generated; the
    /// order is deterministic because the fragment worklist is.
    pub(crate) fn declare_function(&mut self, declaration: impl Display) {
        writeln!(self.function_declarations, "{declaration};").expect(WRITE_TO_STRING);
    }

    /// Adds a function definition written by `print`.
    pub(crate) fn define_function(&mut self, print: impl FnOnce(&mut String) -> fmt::Result) {
        start_definition(&mut self.function_definitions);
        print(&mut self.function_definitions).expect(WRITE_TO_STRING);
        self.function_definitions.push('\n');
    }

    /// Adds a `main` that runs the given Ray entry point.
    pub(crate) fn define_entry_point(&mut self, entry_point: DefinitionName) {
        start_definition(&mut self.function_definitions);
        writeln!(self.function_definitions, "int main(void) {{ return {entry_point}(); }}")
            .expect(WRITE_TO_STRING);
    }

    /// Adds every aggregate of `registry`, each after the aggregates it
    /// contains by value.
    pub(crate) fn define_aggregates(&mut self, registry: &AggregateRegistry) {
        for (name, aggregate, handler_layout) in registry.in_definition_order() {
            writeln!(self.aggregate_declarations, "typedef struct {name} {};", name.typedef())
                .expect(WRITE_TO_STRING);
            let definition = AggregateDefinition::new(aggregate, handler_layout);
            start_definition(&mut self.aggregate_definitions);
            writeln!(self.aggregate_definitions, "{definition}").expect(WRITE_TO_STRING);
        }
    }
}

impl Display for TranslationUnit {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(PRELUDE)?;
        let sections = [
            ("Aggregate type forward declarations", &self.aggregate_declarations),
            ("Aggregate type definitions", &self.aggregate_definitions),
            ("Function forward declarations", &self.function_declarations),
            ("Function definitions", &self.function_definitions),
        ];
        for (heading, contents) in sections {
            // Contents are newline-terminated lines, so a blank line follows.
            write!(formatter, "/* {heading} */\n{contents}\n")?;
        }
        Ok(())
    }
}

/// Separates a definition from the previous one with a blank line.
fn start_definition(buffer: &mut String) {
    if !buffer.is_empty() {
        buffer.push('\n');
    }
}
