[package]
name = "rayc_arena"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
arbitrary = ["dep:proptest"]

[dependencies]
qbice.workspace = true
rayc_hash = { path = "../hash" }
proptest = { workspace = true, optional = true }

[dev-dependencies]
proptest = { workspace = true }

[lints]
workspace = true
