[package]
name = "rayc_syntax"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
arbitrary = ["dep:proptest", "rayc_lexical/arbitrary", "dep:rayc_test_input"]

[dependencies]
rayc_lexical = { path = "../lexical" }
rayc_parser = { path = "../parser" }
rayc_test_input = { path = "../../base/test_input", optional = true }
rayc_source_file = { path = "../../base/source_file" }
rayc_target = { path = "../../base/target" }
rayc_qbice.path = "../../base/qbice"
qbice.workspace = true
proptest = { workspace = true, optional = true }
enum-as-inner = { workspace = true }
derive_more = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
rayc_source_file = { path = "../../base/source_file" }
rayc_lexical = { path = "../lexical", features = ["arbitrary"] }
rayc_test_input = { path = "../../base/test_input" }
rayc_target = { path = "../../base/target" }
rayc_handler = { path = "../../base/handler" }
proptest = { workspace = true }

[lints]
workspace = true
