[package]
name = "rayc_source_file"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
rayc_arena = { path = "../arena" }
rayc_target = { path = "../target" }
rayc_extend = { path = "../extend" }
rayc_qbice.path = "../qbice"
thiserror = { workspace = true }
dashmap = { workspace = true }
getset = { workspace = true }
fxhash = { workspace = true }
siphasher = { workspace = true }
rayon = { workspace = true }
qbice.workspace = true
ropey.workspace = true

[lints]
workspace = true
