//! Allocation of inference variables for a [`crate::Solver`].
//!
//! Every inference variable a solver hands out, whether requested by its
//! caller or created internally (e.g. a fresh tail during row unification),
//! comes from its generator. A caller that needs to know which variables were
//! created installs its own generator and downcasts it back afterwards.

use std::{any::Any, fmt::Debug};

use rayc_type::ty::{InferenceConstraint, TyKind, inference::Inference};

/// Creates the inference variables of one solver.
///
/// Every generated variable must be distinct from all variables previously
/// generated by the same generator.
pub trait InferenceGenerator: Any + Debug + Send + Sync {
    fn generate(&mut self, kind: TyKind, constraint: InferenceConstraint) -> Inference;

    fn as_any(&self) -> &dyn Any;

    fn as_any_mut(&mut self) -> &mut dyn Any;
}

/// Numbers inference variables sequentially without recording them.
///
/// Not `Copy`: a copy would hand out the same variables again.
#[allow(missing_copy_implementations)]
#[derive(Debug, Default)]
pub struct CountingInferenceGenerator {
    counter: u64,
}

impl InferenceGenerator for CountingInferenceGenerator {
    fn generate(&mut self, kind: TyKind, constraint: InferenceConstraint) -> Inference {
        let inference = Inference::new_with_constraint(kind, constraint, self.counter);
        self.counter += 1;
        inference
    }

    fn as_any(&self) -> &dyn Any { self }

    fn as_any_mut(&mut self) -> &mut dyn Any { self }
}
