//! Deferred obligations generated by symbol resolution.

use qbice::{Decode, Encode, Identifiable, StableHash, storage::intern::Interned};
use rayc_diagnostic::{ByteIndex, Highlight, Note, Rendered, Report};
use rayc_lexical::tree::RelativeSpan;
use rayc_qbice::TrackedEngine;
use rayc_symbol::{GlobalSymbolID, name::get_qualified_name, source_map::to_absolute_span};
use rayc_type::{
    constraint::{instance_trait_ref::InstanceTraitRef, ty_relate::TyRelate},
    subst::{Subst, Substitutable},
    ty::Ty,
    where_clause::{MarkerPredicate, OutlivesPredicate, PredicateKind, get_where_clause},
};

#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, StableHash, Encode, Decode, Identifiable,
)]
pub enum Obligation {
    /// An explicit given argument must implement the required trait reference.
    TraitRefCheck(TraitRefCheck),
    /// The instantiated where clause of a resolved symbol must hold at the
    /// resolution site.
    WfCheck(WfCheck),
    /// A reference type `&'a t` is well-formed only if `t: 'a`.
    ReferenceWf(ReferenceWf),
}

/// A deferred check of a resolved symbol's instantiated where clause.
#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, StableHash, Encode, Decode, Identifiable,
)]
pub struct WfCheck {
    symbol_id: GlobalSymbolID,
    subst: Subst,
    span: RelativeSpan,
}

impl WfCheck {
    #[must_use]
    pub const fn new(symbol_id: GlobalSymbolID, subst: Subst, span: RelativeSpan) -> Self {
        Self { symbol_id, subst, span }
    }

    /// Queries and instantiates the predicates after semantic construction has
    /// completed.
    ///
    /// These are every predicate of the where clause, so a struct also
    /// requires its inferred outlives predicates.
    pub async fn predicate_obligations(&self, engine: &TrackedEngine) -> Vec<PredicateObligation> {
        let where_clause = engine.get_where_clause(self.symbol_id).await;
        where_clause
            .predicates()
            .map(|predicate| {
                let kind = predicate.kind().apply_subst_or_clone(&self.subst, engine);
                PredicateObligation::new(kind, self.symbol_id, self.span)
            })
            .collect()
    }
}

/// A deferred check that a written reference type `&'a t` is well-formed,
/// which requires `t: 'a`.
#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, StableHash, Encode, Decode, Identifiable,
)]
pub struct ReferenceWf {
    pointee: Interned<Ty>,
    lifetime: Interned<Ty>,
    span: RelativeSpan,
}

impl ReferenceWf {
    #[must_use]
    pub const fn new(pointee: Interned<Ty>, lifetime: Interned<Ty>, span: RelativeSpan) -> Self {
        Self { pointee, lifetime, span }
    }

    /// Returns the outlives requirement that makes the reference well-formed.
    #[must_use]
    pub fn predicate(&self) -> OutlivesPredicate {
        OutlivesPredicate::new(self.pointee.clone(), self.lifetime.clone())
    }

    /// Returns the span of the written reference type.
    #[must_use]
    pub const fn span(&self) -> RelativeSpan { self.span }
}

impl Substitutable for ReferenceWf {
    fn apply_subst(&self, subst: &Subst, engine: &TrackedEngine) -> Option<Self> {
        match (self.pointee.apply_subst(subst, engine), self.lifetime.apply_subst(subst, engine)) {
            (None, None) => None,
            (pointee, lifetime) => Some(Self::new(
                pointee.unwrap_or_else(|| self.pointee.clone()),
                lifetime.unwrap_or_else(|| self.lifetime.clone()),
                self.span,
            )),
        }
    }
}

impl Report for ReferenceWf {
    async fn report(&self, engine: &TrackedEngine) -> Rendered<ByteIndex> {
        let pointee = self.pointee.display(engine).await;
        let lifetime = self.lifetime.display(engine).await;

        Rendered::builder()
            .message(format!("the type `{pointee}` may not live long enough"))
            .primary_highlight(Highlight::new(
                engine.to_absolute_span(&self.span).await,
                Some(format!("the reference requires `{pointee}: {lifetime}`")),
            ))
            .help_message(format!("consider adding `where ({pointee}: {lifetime})`"))
            .build()
    }
}

/// A substituted where-clause predicate required by a resolved symbol.
#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, StableHash, Encode, Decode, Identifiable,
)]
pub struct PredicateObligation {
    predicate: PredicateKind,
    symbol_id: GlobalSymbolID,
    span: RelativeSpan,
}

/// The solver constraint represented by one where-clause predicate.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, StableHash, Encode, Decode)]
pub enum PredicateConstraint {
    TyRelate(TyRelate),
    Marker(MarkerPredicate),
    Outlives(OutlivesPredicate),
}

impl PredicateObligation {
    #[must_use]
    pub const fn new(
        predicate: PredicateKind,
        symbol_id: GlobalSymbolID,
        span: RelativeSpan,
    ) -> Self {
        Self { predicate, symbol_id, span }
    }

    #[must_use]
    pub const fn predicate(&self) -> &PredicateKind { &self.predicate }

    /// Returns the span of the use that requires the predicate.
    #[must_use]
    pub const fn span(&self) -> RelativeSpan { self.span }

    #[must_use]
    pub fn constraint(&self) -> PredicateConstraint {
        match &self.predicate {
            PredicateKind::AssociatedTypeEquality(equality) => PredicateConstraint::TyRelate(
                TyRelate::new_invariant(equality.left().clone(), equality.right().clone()),
            ),
            PredicateKind::Marker(predicate) => PredicateConstraint::Marker(predicate.clone()),
            PredicateKind::Outlives(predicate) => PredicateConstraint::Outlives(predicate.clone()),
        }
    }
}

impl Substitutable for PredicateObligation {
    fn apply_subst(&self, subst: &Subst, engine: &TrackedEngine) -> Option<Self> {
        self.predicate
            .apply_subst(subst, engine)
            .map(|predicate| Self::new(predicate, self.symbol_id, self.span))
    }
}

impl PredicateObligation {
    /// Describes what the predicate requires, as in "`t` must equal `u`".
    async fn describe_requirement(&self, engine: &TrackedEngine) -> String {
        match &self.predicate {
            PredicateKind::AssociatedTypeEquality(equality) => {
                let left = equality.left().display(engine).await;
                let right = equality.right().display(engine).await;
                format!("`{left}` must equal `{right}`")
            }
            PredicateKind::Marker(predicate) => {
                let implementor = predicate.implementor().display(engine).await;
                let marker = engine.get_qualified_name(predicate.marker_id()).await;
                format!("`{implementor}` must satisfy marker `{marker}`")
            }
            PredicateKind::Outlives(predicate) => {
                let subject = predicate.lesser().display(engine).await;
                let bound = predicate.greater().display(engine).await;
                format!("`{subject}` must outlive `{bound}`")
            }
        }
    }
}

impl Report for PredicateObligation {
    async fn report(&self, engine: &TrackedEngine) -> Rendered<ByteIndex> {
        let name = engine.get_qualified_name(self.symbol_id).await;
        let requirement = self.describe_requirement(engine).await;

        Rendered::builder()
            .message(format!("where-clause obligation for `{name}` is not satisfied"))
            .primary_highlight(Highlight::new(
                engine.to_absolute_span(&self.span).await,
                Some(requirement),
            ))
            .build()
    }
}

#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, StableHash, Encode, Decode, Identifiable,
)]
pub struct TraitRefCheck {
    constraint: InstanceTraitRef,
    span: RelativeSpan,
}

impl TraitRefCheck {
    #[must_use]
    pub const fn new(constraint: InstanceTraitRef, span: RelativeSpan) -> Self {
        Self { constraint, span }
    }

    #[must_use]
    pub const fn constraint(&self) -> &InstanceTraitRef { &self.constraint }

    #[must_use]
    pub fn into_constraint(self) -> InstanceTraitRef { self.constraint }
}

impl Substitutable for TraitRefCheck {
    fn apply_subst(&self, subst: &Subst, engine: &TrackedEngine) -> Option<Self> {
        self.constraint
            .apply_subst(subst, engine)
            .map(|constraint| Self::new(constraint, self.span))
    }
}

impl TraitRefCheck {
    /// Describes the given argument and the trait reference it must
    /// implement, as in `main.EqInt` and `main.Eq[int32]`.
    async fn describe(&self, engine: &TrackedEngine) -> (String, String) {
        let expected = self.constraint.expected();
        let name = engine.get_qualified_name(expected.trait_id()).await;
        let mut args = Vec::new();
        for arg in expected.args().iter() {
            args.push(arg.display(engine).await.to_string());
        }
        let instance = if let rayc_type::ty::Ty::Application(application) =
            &**self.constraint.instance()
            && let rayc_type::ty::application::View::Instance(instance) = application.view()
        {
            engine.get_qualified_name(instance.symbol_id()).await
        } else {
            self.constraint.instance().display(engine).await.to_string()
        };
        (instance, format!("{name}[{}]", args.join(", ")))
    }
}

impl Report for TraitRefCheck {
    async fn report(&self, engine: &TrackedEngine) -> Rendered<ByteIndex> {
        let (instance, trait_ref) = self.describe(engine).await;
        Rendered::builder()
            .message(format!("given argument `{instance}` does not implement `{trait_ref}`"))
            .primary_highlight(Highlight::new(engine.to_absolute_span(&self.span).await, None))
            .build()
    }
}

/// The obligation whose types, when related, required a lifetime relation.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum RelationOrigin {
    /// Relating an explicit given argument's trait reference to the required
    /// one.
    TraitRefCheck(TraitRefCheck),

    /// Relating the two sides of an instantiated where-clause equality.
    Predicate(PredicateObligation),
}

impl RelationOrigin {
    /// Returns where the obligation arises.
    #[must_use]
    pub const fn span(&self) -> RelativeSpan {
        match self {
            Self::TraitRefCheck(check) => check.span,
            Self::Predicate(predicate) => predicate.span,
        }
    }

    /// Explains why the obligation requires the lifetime relation.
    async fn describe(&self, engine: &TrackedEngine) -> String {
        match self {
            Self::TraitRefCheck(check) => {
                let (instance, trait_ref) = check.describe(engine).await;
                format!("this is required when checking that `{instance}` implements `{trait_ref}`")
            }
            Self::Predicate(predicate) => {
                let name = engine.get_qualified_name(predicate.symbol_id).await;
                let requirement = predicate.describe_requirement(engine).await;
                format!("this is required by the where clause of `{name}`: {requirement}")
            }
        }
    }
}

/// An outlives predicate between two lifetimes that relating the types of an
/// obligation requires, which the outlives facts at the site do not entail.
///
/// Lifetimes never decide whether two types relate, so such a relation
/// succeeds and reports the lifetimes it could not prove separately.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct UnsatisfiedRelationOutlives {
    predicate: OutlivesPredicate,
    origin: RelationOrigin,
}

impl UnsatisfiedRelationOutlives {
    #[must_use]
    pub const fn new(predicate: OutlivesPredicate, origin: RelationOrigin) -> Self {
        Self { predicate, origin }
    }
}

impl Report for UnsatisfiedRelationOutlives {
    async fn report(&self, engine: &TrackedEngine) -> Rendered<ByteIndex> {
        let lesser = self.predicate.lesser().display(engine).await;
        let greater = self.predicate.greater().display(engine).await;

        Rendered::builder()
            .message(format!("lifetime `{lesser}` does not outlive `{greater}`"))
            .primary_highlight(Highlight::new(
                engine.to_absolute_span(&self.origin.span()).await,
                Some(format!("requires `{lesser}: {greater}`")),
            ))
            .help_message(format!("consider adding `where ({lesser}: {greater})`"))
            .notes(vec![Note::builder().message(self.origin.describe(engine).await).build()])
            .build()
    }
}
