[package]
name = "rayc_resolution"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
bon.workspace = true
qbice.workspace = true
rayc_diagnostic.path = "../../base/diagnostic"
rayc_handler.path = "../../base/handler"
rayc_lexical.path = "../../syntax/lexical"
rayc_qbice.path = "../../base/qbice"
rayc_source_file.path = "../../base/source_file"
rayc_symbol.path = "../symbol"
rayc_syntax.path = "../../syntax/syntax"
rayc_type.path = "../type"

[lints]
workspace = true
