use std::io::{self, Write};

use rayc_mono::{MonoFunction, collect_target};
use rayc_qbice::TrackedEngine;
use rayc_symbol::GlobalSymbolID;
use rayc_target::TargetID;
use rayc_type::subst::Subst;

use crate::{
    context::{Context, instantiation::MonoFunctionSubstID},
    identifier::Identifier,
    writer::Writer,
};

/// Options controlling the contents of a generated C translation unit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CTranslationUnitOptions {
    entry_point: Option<GlobalSymbolID>,
}

impl CTranslationUnitOptions {
    /// Creates options for an ordinary translation unit without a C entry
    /// point wrapper.
    #[must_use]
    pub const fn ordinary() -> Self { Self { entry_point: None } }

    /// Creates options for an executable translation unit targeting the given
    /// validated Ray entry point.
    #[must_use]
    pub const fn executable(entry_point: GlobalSymbolID) -> Self {
        Self { entry_point: Some(entry_point) }
    }
}

/// Writes a complete C translation unit for `target_id` to `buf`.
pub async fn write_c_translation_unit(
    engine: &TrackedEngine,
    target_id: TargetID,
    options: CTranslationUnitOptions,
    buf: &mut impl Write,
) -> io::Result<()> {
    let mono_program = collect_target(engine, target_id).await;
    let mono_functions = mono_program.functions().cloned().collect::<Vec<_>>();
    let mut generator = Context::new(engine.clone(), mono_program);
    let mut function_definitions = Vec::with_capacity(mono_functions.len());

    for mono_function in &mono_functions {
        let mut definition = Vec::new();
        let mut writer = Writer::new(&mut definition);
        writer.generate_function_definition(mono_function, &mut generator).await?;
        function_definitions.push(definition);
    }

    writeln!(buf, "/* This file is auto generated by Ray compiler */")?;
    writeln!(buf, "#include <stdint.h>")?;
    writeln!(buf, "#include <stdbool.h>")?;

    writeln!(buf)?;
    writeln!(buf, "/* Composite type forward declarations */")?;

    generator.write_forward_decl_tuples(buf)?;

    writeln!(buf)?;
    writeln!(buf, "/* Composite type definitions */")?;

    generator.write_tuple_struct_defs(buf)?;

    writeln!(buf)?;
    writeln!(buf, "/* Function forward declarations */")?;

    for mono_function in &mono_functions {
        generator.write_mono_function_decl(mono_function, buf).await?;
        writeln!(buf, ";")?;
    }

    writeln!(buf)?;
    writeln!(buf, "/* Function definitions */")?;

    for definition in function_definitions {
        buf.write_all(&definition)?;
        writeln!(buf)?;
        writeln!(buf)?;
    }

    if let Some(entry_point) = options.entry_point {
        let entry_point = MonoFunction::new(entry_point, Subst::new_empty());
        let entry_point_name = generator.get_def_name(entry_point.def_id()).await;
        let subst_id = MonoFunctionSubstID::for_function(&entry_point);
        writeln!(
            buf,
            "int main(void) {{ return {}(); }}",
            Identifier::def(&entry_point_name, subst_id)
        )?;
    }

    Ok(())
}
