use std::io::{self, Write};

use rayc_mono::{MonoError, collect_target};
use rayc_qbice::TrackedEngine;
use rayc_symbol::{GlobalSymbolID, symbol_kind::get_all_def_ids};
use rayc_target::TargetID;

use crate::{
    context::{Context, instantiation::CDef},
    identifier::Identifier,
    writer::Writer,
};

/// An error encountered while collecting or writing a C translation unit.
#[derive(Debug, thiserror::Error)]
pub enum CTranslationUnitError {
    /// Monomorphization could not produce a concrete target inventory.
    #[error(transparent)]
    Mono(#[from] MonoError),

    /// Writing the generated C source failed.
    #[error(transparent)]
    Io(#[from] io::Error),
}

/// Options controlling the contents of a generated C translation unit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CTranslationUnitOptions {
    entry_point: Option<GlobalSymbolID>,
}

impl CTranslationUnitOptions {
    /// Creates options for an ordinary translation unit without a C entry
    /// point wrapper.
    #[must_use]
    pub const fn ordinary() -> Self { Self { entry_point: None } }

    /// Creates options for an executable translation unit targeting the given
    /// validated Ray entry point.
    #[must_use]
    pub const fn executable(entry_point: GlobalSymbolID) -> Self {
        Self { entry_point: Some(entry_point) }
    }
}

/// Writes a complete C translation unit for `target_id` to `buf`.
pub async fn write_c_translation_unit(
    engine: &TrackedEngine,
    target_id: TargetID,
    options: CTranslationUnitOptions,
    buf: &mut impl Write,
) -> Result<(), CTranslationUnitError> {
    let mono_program = collect_target(engine, target_id).await?;
    let mut generator = Context::new(engine.clone(), mono_program);

    if let Some(entry_point) = options.entry_point {
        let entry_point = CDef::builder().def_id(entry_point).build();
        let _ = generator.get_cdef_id(entry_point).await;
    }

    let def_ids = engine.get_all_def_ids(target_id).await;

    for def_id in def_ids.iter().copied() {
        let cdef = CDef::builder().def_id(target_id.make_global(def_id)).build();
        let _ = generator.get_cdef_id(cdef).await;
    }

    let cdef_ids = generator.cdef_decl_ids().collect::<Vec<_>>();
    let mut function_definitions = Vec::with_capacity(cdef_ids.len());

    for cdef_id in cdef_ids {
        let mut definition = Vec::new();
        let mut writer = Writer::new(&mut definition);
        writer.generate_function_definition(cdef_id, &mut generator).await?;
        function_definitions.push(definition);
    }

    writeln!(buf, "/* This file is auto generated by Ray compiler */")?;
    writeln!(buf, "#include <stdint.h>")?;
    writeln!(buf, "#include <stdbool.h>")?;

    writeln!(buf)?;
    writeln!(buf, "/* Composite type forward declarations */")?;

    generator.write_forward_decl_tuples(buf)?;

    writeln!(buf)?;
    writeln!(buf, "/* Composite type definitions */")?;

    generator.write_tuple_struct_defs(buf)?;

    writeln!(buf)?;
    writeln!(buf, "/* Function forward declarations */")?;

    generator.write_forward_decl_cdefs(buf).await?;

    writeln!(buf)?;
    writeln!(buf, "/* Function definitions */")?;

    for definition in function_definitions {
        buf.write_all(&definition)?;
        writeln!(buf)?;
        writeln!(buf)?;
    }

    if let Some(entry_point) = options.entry_point {
        let entry_point_name = generator.get_def_name(entry_point).await;
        writeln!(buf, "int main(void) {{ return {}(); }}", Identifier::def(&entry_point_name))?;
    }

    Ok(())
}
