use std::io::{self, Write};

use rayc_qbice::TrackedEngine;
use rayc_symbol::symbol_kind::get_all_def_ids;
use rayc_target::TargetID;

use crate::{
    context::{Context, instantiation::CDef},
    writer::Writer,
};

/// Writes a complete C translation unit for `target_id` to `buf`.
pub async fn write_c_translation_unit(
    engine: &TrackedEngine,
    target_id: TargetID,
    buf: &mut impl Write,
) -> io::Result<()> {
    let mut generator = Context::new(engine.clone());
    let def_ids = engine.get_all_def_ids(target_id).await;

    for def_id in def_ids.iter().copied() {
        let cdef = CDef::builder().def_id(target_id.make_global(def_id)).build();
        let _ = generator.get_cdef_id(cdef).await;
    }

    let cdef_ids = generator.cdef_decl_ids().collect::<Vec<_>>();
    let mut function_definitions = Vec::with_capacity(cdef_ids.len());

    for cdef_id in cdef_ids {
        let mut definition = Vec::new();
        let mut writer = Writer::new(&mut definition);
        writer.generate_function_definition(cdef_id, &mut generator).await?;
        function_definitions.push(definition);
    }

    writeln!(buf, "/* This file is auto generated by Ray compiler */")?;
    writeln!(buf, "#include <stdint.h>")?;
    writeln!(buf, "#include <stdbool.h>")?;

    writeln!(buf)?;
    writeln!(buf, "/* Composite type forward declarations */")?;

    generator.write_forward_decl_tuples(buf)?;

    writeln!(buf)?;
    writeln!(buf, "/* Composite type definitions */")?;

    generator.write_tuple_struct_defs(buf)?;

    writeln!(buf)?;
    writeln!(buf, "/* Function forward declarations */")?;

    generator.write_forward_decl_cdefs(buf).await?;

    writeln!(buf)?;
    writeln!(buf, "/* Function definitions */")?;

    for definition in function_definitions {
        buf.write_all(&definition)?;
        writeln!(buf)?;
        writeln!(buf)?;
    }

    Ok(())
}
