[package]
name = "rayc_source_file_impl"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
rayc_source_file.path = "../source_file"
rayc_qbice.path = "../qbice"
rayc_target.path = "../target"
qbice.workspace = true
linkme.workspace = true
siphasher.workspace = true

[lints]
workspace = true
