[package]
name = "rayc_c"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
rayc_hash.path = "../../base/hash"
rayc_target.path = "../../base/target"
rayc_symbol.path = "../../semantic/symbol"
rayc_qbice.path = "../../base/qbice"
rayc_ir.path = "../../semantic/ir"
rayc_type.path = "../../semantic/type"
rayc_semantic_element.path = "../../semantic/semantic_element"
qbice.workspace = true
bon.workspace = true

[dev-dependencies]
rayc_arena.path = "../../base/arena"
rayc_lexical.path = "../../syntax/lexical"
rayc_source_file.path = "../../base/source_file"
tokio.workspace = true

[lints]
workspace = true
